export const CFG = Object.freeze({
  version: '1.6.0',
  keys: Object.freeze({
    theme:             'fmc_theme_v1',
    vehicles:          'fmc_vehicles_v1',
    activeVehicle:     'fmc_active_v1',
    curPrefix:         'fmc_cur_',
    histPrefix:        'fmc_hist_',
    legacyCurrent:     'fmc_current_v1',
    legacyHistory:     'fmc_history_v1',
    seenVersion:       'fmc_seen_version_v1',
    mapCollapsed:      'fmc_map_collapsed_v1',
    bluetoothSettings: 'fmc_bluetooth_v1',
  }),
  maxHistory:        30,
  maxImgWidth:       900,
  imgQuality:        0.72,
  maxTextLen:        300,
  maxVehicles:       5,
  maxVehicleNameLen: 30,
  maxPlateLen:       15,
  maxColorLen:       20,
  toastDuration:     3000,
  timerInterval:     1000,
  geocodeTimeout:    6000,
  defaultCenter:     [31.7767, 35.2345],
  nominatim:         'https://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1',
  vehicleIcons:      ['🚗', '🚙', '🚕', '🚌', '🏎️', '🛻', '🚐', '🚑'],
  changelog: Object.freeze([
    Object.freeze({
      version: '1.6.0',
      date: '2026-06-30',
      items: Object.freeze([
        'קישור מכשיר Bluetooth לכל רכב לזיהוי אוטומטי',
        'חיבור Bluetooth → הצעה או סיום אוטומטי של חניה פעילה',
        'ניתוק Bluetooth → שמירת חניה אוטומטית לפי GPS',
        'חלון הוספת מדיה (תמונה / הקלטה / תיאור) לאחר שמירה אוטומטית',
        'מסך הגדרות Bluetooth לכלל הרכבים ולכל רכב בנפרד',
      ]),
    }),
    Object.freeze({
      version: '1.5.0',
      date: '2026-06-27',
      items: Object.freeze([
        'תמונה, הקלטה ותיאור מוצגים ישירות בתוך כרטיס החניה',
        'מחיקת תמונה, הקלטה או תיאור בנפרד בלחיצה על כפתור מחיקה',
        'האזנה להקלטה ישירות מהאפליקציה ללא פתיחת חלון נוסף',
        'עריכת תיאור ישירות מכרטיס החניה',
      ]),
    }),
    Object.freeze({
      version: '1.4.0',
      date: '2026-06-26',
      items: Object.freeze([
        'לחיצה על "חניה פעילה" בכותרת פותחת את מסך סיום החניה',
        'פרטי רכב נוספים: לוחית רישוי וצבע (שדות אופציונליים)',
      ]),
    }),
    Object.freeze({
      version: '1.3.0',
      date: '2026-06-26',
      items: Object.freeze([
        'מספר גרסה גלוי בכותרת האפליקציה',
        'חלון "מה חדש" מוצג בכל עדכון',
        'תיקון תצוגת מפה ואיתחול מחדש',
        'כפתור הסתרת / הצגת המפה',
        'ניקוי חניה נוכחית לפי רכב מתצוגת הרכבים',
      ]),
    }),
    Object.freeze({
      version: '1.2.0',
      date: '2026-06-25',
      items: Object.freeze([
        'תמיכה במספר רכבים (עד 5)',
        'שיתוף ב-WhatsApp עם בחירת תוכן',
        'חבילת בדיקות אוטומטיות (Vitest + Playwright)',
      ]),
    }),
  ]),
});
